spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/designpattern
      username: root
      password: 112233
      driver-class-name: com.mysql.cj.jdbc.Driver
